### ISSUE TITLE
Running with "run" argument considered ambigious

### ISSUE THREAD

**Issue by ammaraskar** [python/benchmarks#1]
Not sure if this belongs here but right now running bench.py with `run` brings up this error. It seems like there's an active issue for this: https://bugs.python.org/issue14365 

```bash
> ..\python_d.exe bench.py run
usage: bench.py [-h] {run,compare,run_compare,list,list_groups} ...
bench.py: error: argument action: ambiguous choice: 'run' could match run, run_compare
```

As a workaround I changed my `run` to `run_local` in https://github.com/python/benchmarks/blob/master/benchmark/cli.py#L84
and
https://github.com/python/benchmarks/blob/master/benchmark/cli.py#L150
and
https://github.com/python/benchmarks/blob/master/benchmark/run.py#L445

**Comment by haypo** [comment]
Strange. I'm unable to reproduce the issue on Fedora 24 with Python 2.7.11 nor Python 3.5.1.

**Comment by zware** [comment]
This appears to be a bug introduced in http://bugs.python.org/issue12713

**Comment by haypo** [comment]
Why do you close the issue? We should fix it or workaround it.

**Comment by ammaraskar** [comment]
Well it's an upstream issue, no need to keep it open here, right?

**Comment by zware** [comment]
Because it was just introduced into 3.6 yesterday, and ought to be fixed (or reverted) very soon.

**Comment by haypo** [comment]
> Because it was just introduced into 3.6 yesterday, and ought to be fixed
(or reverted) very soon.

Oh, Ammar: you compiled manually the default branch of Python on Windows?

**Comment by ammaraskar** [comment]
Yup, latest default.

**Comment by haypo** [comment]
> Yup, latest default.

Oh ok, fine :-) Use an older version of argparse to workaround the issue (or an older version of the repository).

**Comment by vsajip** [comment]
That recent change to `argparse` which caused your breakage has now been reverted. Sorry :-(
