### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by brettcannon** [python/benchmarks#7]
With caching turn on in the `.travis.yml` file, the base set of benchmarks should complete for a single run before Travis times out and kills the VM. That would be enough to make sure simple things like the `django` -> `django_template` rename breakage don't occur again.

**Comment by haypo** [comment]
For tests, I'm using --debug-single-sample command line option: it asks to only run each benchmark once using a single worker process (or maybe even no worker process at all, depending on the benchmark is run).

* "python3 bench.py run --debug-single-sample" => 14 seconds (10 benchmarks)
* "python3 bench.py run --debug-single-sample -b all" => 28 seconds (44 benchmarks)

The purpose of tests is to check that running benchmarks work, not to check the results.

**Comment by haypo** [comment]
Done: see .travis.yaml.
